### ISSUE TITLE
Liste déroulante

### ISSUE THREAD

**Issue by ocots** [control-toolbox/preconditioning#3]
Voir ici : https://github.com/control-toolbox/medical_resonance_imaging/blob/a125f1819cc6b23f0860d01d8eac1a28ae06d4d5/docs/src/saturation.md?plain=1#L175

**Comment by remydutto** [comment]
Fait dans le commit [6e1feb9](https://github.com/control-toolbox/preconditioning/commit/6e1feb9582eb491d87c193bcadff5afb6c4f4576)
