### ISSUE TITLE
Add compat

### ISSUE THREAD

**Issue by ocots** [control-toolbox/preconditioning#4]
See this [Project.toml](https://github.com/control-toolbox/medical_resonance_imaging/blob/main/docs/Project.toml).

Then, add in the introduction the [following lines](https://github.com/control-toolbox/medical_resonance_imaging/blob/a125f1819cc6b23f0860d01d8eac1a28ae06d4d5/docs/src/index.md?plain=1#L80).

**Comment by remydutto** [comment]
Done in the commit [6e1feb9](https://github.com/control-toolbox/preconditioning/commit/6e1feb9582eb491d87c193bcadff5afb6c4f4576).
