### ISSUE TITLE
Print the trace in the documentation

### ISSUE THREAD

**Issue by remydutto** [control-toolbox/preconditioning#5]
In the 2D-example documentation, i cannot see the trace of the fsolve function while the showtrace is set to true.

**Comment by jbcaillau** [comment]
mr @ocots uses `nothing # hide` a lot 🤭

**Comment by ocots** [comment]
Which branch?

**Comment by ocots** [comment]
You should not merge while it is not working. The process:

- create an issue
- from the issue, create a branch
- you can make a PR but you should convert it as a draft while you are working on it
- when it is ok you can switch to "ready to review"

**Comment by ocots** [comment]
@remydutto Tu remarqueras un "Show trace now #6" qui correspond à la PR en cours car cette issue est liée à la PR https://github.com/control-toolbox/preconditioning/pull/6.
